// GENERATED FILE - DO NOT EDIT BY HAND.
//
// Generated by RokctAI/shared-workflows scripts/tour/merge_fragments.py from
// this app's tour/app.tour.yaml plus the tour fragments shipped by the
// composed SDKs (each SDK's templates/tour/<sdk>.tour.yaml). CI regenerates
// it on every guided-tour run; the committed copy exists so the repo
// analyzes and compiles without running the merge first.
//
// ignore_for_file: unused_import, always_specify_types, avoid_redundant_argument_values
// ignore_for_file: unawaited_futures, use_build_context_synchronously
// ignore_for_file: implementation_imports, directives_ordering, depend_on_referenced_packages

import 'package:auto_route/auto_route.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:auth_sdk/src/common/application/auth/auth.dart';
import 'package:base_sdk/src/models/response/languages_response.dart';
import 'package:base_sdk/src/services/app_helpers.dart';
import 'package:base_sdk/src/services/local_storage.dart';
import 'package:base_sdk/src/services/tr_keys.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:remixicon/remixicon.dart';

typedef TourAction = Future<void> Function(
    WidgetTester tester, StackRouter router);

class TourStep {
  const TourStep(this.key, this.settleMs, this.screenshot, this.action);

  final String key;
  final int settleMs;

  /// False for steps that only perform an action (no still captured).
  final bool screenshot;
  final TourAction action;
}

/// Runs once before the app is launched.
Future<void> tourSetup() async {
  // Pre-seed the language so the first-run language picker can never
  // block the tour behind a non-dismissible modal (the backend may
  // advertise several languages). LocalStorage.init() is idempotent -
  // app.main() calls it again.
  await LocalStorage.init();
  if (LocalStorage.getLanguage() == null) {
    await LocalStorage.setLanguageData(LanguageData(
      id: '1',
      title: 'English',
      locale: 'en',
      backward: false,
      isDefault: true,
      active: true,
    ));
    await LocalStorage.setLanguageSelected(true);
    await LocalStorage.setLangLtr(false);
  }
}

final List<TourStep> tourSteps = <TourStep>[
  TourStep('welcome', 12000, true, (WidgetTester tester, StackRouter router) async {
    // wait: settle only.
  }),
  TourStep('auth_login', 5000, true, (WidgetTester tester, StackRouter router) async {
    // Land on /login (the welcome screen), then open the login sheet the
    // way a user does - via its Login button.
    router.replaceNamed('/login');
    await Future<void>.delayed(const Duration(seconds: 3));
    await tester.tap(
      find.text(AppHelpers.getTranslation(TrKeys.login)).first,
      warnIfMissed: false,
    );
  }),
  TourStep('auth_register', 5000, true, (WidgetTester tester, StackRouter router) async {
    // Close the login sheet, then open the register sheet from the
    // welcome screen's Register button.
    final NavigatorState navigator =
        tester.state(find.byType(Navigator).first);
    if (navigator.canPop()) {
      navigator.pop();
      await Future<void>.delayed(const Duration(seconds: 2));
    }
    await tester.tap(
      find.text(AppHelpers.getTranslation(TrKeys.register)).first,
      warnIfMissed: false,
    );
  }),
  TourStep('auth_reset_password', 5000, true, (WidgetTester tester, StackRouter router) async {
    // Close the register sheet, reopen the login sheet, then tap
    // "Forgot password" - its handler swaps the login sheet for the
    // reset-password sheet, exactly the path a user takes.
    final NavigatorState navigator =
        tester.state(find.byType(Navigator).first);
    if (navigator.canPop()) {
      navigator.pop();
      await Future<void>.delayed(const Duration(seconds: 2));
    }
    await tester.tap(
      find.text(AppHelpers.getTranslation(TrKeys.login)).first,
      warnIfMissed: false,
    );
    await Future<void>.delayed(const Duration(seconds: 3));
    await tester.tap(
      find.text(AppHelpers.getTranslation(TrKeys.forgotPassword)).first,
      warnIfMissed: false,
    );
  }),
  TourStep('auth_back_to_login', 3000, false, (WidgetTester tester, StackRouter router) async {
    final NavigatorState navigator =
        tester.state(find.byType(Navigator).first);
    // Bounded: at most one sheet is open, but stay safe against strays.
    for (int i = 0; i < 5 && navigator.canPop(); i++) {
      navigator.pop();
      await Future<void>.delayed(const Duration(milliseconds: 500));
    }
    router.replaceNamed('/login');
  }),
  TourStep('demo_sign_in', 6000, false, (WidgetTester tester, StackRouter router) async {
    final Element element = tester.element(find.byType(Navigator).first);
    final ProviderContainer container =
        ProviderScope.containerOf(element, listen: false);
    // loginProvider is autoDispose: hold a subscription so the notifier
    // survives between the field writes and the login call.
    final ProviderSubscription<dynamic> subscription =
        container.listen(loginProvider, (_, __) {});
    try {
      final login = container.read(loginProvider.notifier);
      login.setEmail('demo.student@example.com');
      login.setPassword('demo-learners-2026');
      // MockAuthRepository accepts any password, but the ADDRESS decides the
      // role it hands back (MockAuthRepository._demoRolesByEmail), and the
      // role decides whether this app's session_policy admits the session at
      // all. So each shell picks its own account with setup.demo_email in its
      // tour/app.tour.yaml; shells that leave it unset get the 'customer'
      // default. The timeout guards the post-session FCM sync, which can
      // stall on an emulator - navigation to the demo landing happens before
      // it, so a timeout is harmless.
      await login
          .login(element)
          .timeout(const Duration(seconds: 45), onTimeout: () {});
    } finally {
      subscription.close();
    }
  }),
  TourStep('launcher_home', 8000, true, (WidgetTester tester, StackRouter router) async {
    router.replaceNamed('/launcher');
  }),
  TourStep('launch_dark_mode', 6000, true, (WidgetTester tester, StackRouter router) async {
    // Make sure the launcher is on screen, then tap the theme toggle in
    // the header. The icon is moon_line in light mode and sun_line in
    // dark mode - tap whichever is present, tolerantly.
    router.replaceNamed('/launcher');
    await Future<void>.delayed(const Duration(seconds: 3));
    final Finder moon = find.byIcon(RemixIcons.moon_line);
    final Finder sun = find.byIcon(RemixIcons.sun_line);
    if (moon.evaluate().isNotEmpty) {
      await tester.tap(moon.first, warnIfMissed: false);
    } else if (sun.evaluate().isNotEmpty) {
      await tester.tap(sun.first, warnIfMissed: false);
    }
  }),
  TourStep('launch_drawer', 5000, true, (WidgetTester tester, StackRouter router) async {
    // Open the app drawer from the handle strip at the foot of the home
    // surface. Tolerant: on a wide capture window the drawer is already
    // a plane beside home and there is no handle to tap.
    final Finder handle = find.byKey(const ValueKey<String>('launcher-drawer-handle'));
    if (handle.evaluate().isNotEmpty) {
      await tester.tap(handle.first, warnIfMissed: false);
    }
  }),
  TourStep('launch_drawer_close', 3000, false, (WidgetTester tester, StackRouter router) async {
    final Finder sheet = find.byKey(const ValueKey<String>('launcher-drawer-sheet'));
    if (sheet.evaluate().isNotEmpty) {
      final Size size = tester.view.physicalSize / tester.view.devicePixelRatio;
      await tester.tapAt(Offset(size.width / 2, 12));
    }
  }),
  TourStep('launch_reset', 4000, false, (WidgetTester tester, StackRouter router) async {
    final Finder sun = find.byIcon(RemixIcons.sun_line);
    if (sun.evaluate().isNotEmpty) {
      await tester.tap(sun.first, warnIfMissed: false);
    }
  }),
  TourStep('base_profile', 7000, true, (WidgetTester tester, StackRouter router) async {
    router.replaceNamed('/generic-profile');
  }),
  TourStep('productivity_tasks', 7000, true, (WidgetTester tester, StackRouter router) async {
    router.replaceNamed('/tasks');
  }),
];
